//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Script.rc
//
#define IDS_MENU_CAPTION_EXTRACT_NORMAL 16
#define IDS_MENU_CAPTION_EXTRACT_DESKTOP 17
#define IDS_MENU_CAPTION_EXTRACT_SAME   18
#define IDS_MENU_CAPTION_EXTRACT_TARGET 19
#define IDS_MENU_ITEM_CAPTION_LZH       21
#define IDS_MENU_ITEM_CAPTION_LZH_SFX   22
#define IDS_MENU_ITEM_CAPTION_ZIP       23
#define IDS_MENU_ITEM_CAPTION_ZIP_SFX   24
#define IDS_MENU_ITEM_CAPTION_ZIP_PASS  25
#define IDS_MENU_ITEM_CAPTION_ZIP_PASS_SFX 26
#define IDS_MENU_ITEM_CAPTION_CAB       27
#define IDS_MENU_ITEM_CAPTION_CAB_SFX   28
#define IDS_MENU_ITEM_CAPTION_7Z        29
#define IDS_MENU_ITEM_CAPTION_7Z_PASS   30
#define IDS_MENU_ITEM_CAPTION_7Z_SFX    31
#define IDS_MENU_ITEM_CAPTION_TAR       32
#define IDS_MENU_ITEM_CAPTION_GZ        33
#define IDS_MENU_ITEM_CAPTION_BZ2       34
#define IDS_MENU_ITEM_CAPTION_TGZ       35
#define IDS_MENU_ITEM_CAPTION_TBZ       36
#define IDS_MENU_ITEM_CAPTION_JACK      37
#define IDS_MENU_ITEM_CAPTION_JACK_SFX  38
#define IDS_MENU_CAPTION_LIST           39
#define IDS_MENU_ITEM_CAPTION_XZ        41
#define IDS_MENU_ITEM_CAPTION_LZMA      42
#define IDS_MENU_ITEM_CAPTION_YZ1       43
#define IDS_MENU_ITEM_CAPTION_YZ1_PASS  44
#define IDS_MENU_ITEM_CAPTION_YZ1_PASS_SFX 45
#define IDS_MENU_ITEM_CAPTION_YZ1_SFX   46
#define IDS_MENU_ITEM_CAPTION_YZ1_PUB_PASS 47
#define IDS_MENU_ITEM_CAPTION_YZ1_PUB_PASS_SFX 48
#define IDS_MENU_ITEM_CAPTION_HKI       49
#define IDS_MENU_ITEM_CAPTION_BZA       50
#define IDS_MENU_ITEM_CAPTION_GZA       51
#define IDS_MENU_ITEM_CAPTION_ISH       52
#define IDS_MENU_ITEM_CAPTION_UUE       53
#define IDS_MENU_ITEM_CAPTION_ZIP_SPLIT 54
#define IDS_MENU_ITEM_CAPTION_ZIP_PASS_SPLIT 55
#define IDS_MENU_ITEM_CAPTION_7Z_SPLIT  56
#define IDS_MENU_ITEM_CAPTION_7Z_PASS_SPLIT 57
#define IDS_MENU_ITEM_CAPTION_TAR_RELATED 58
#define IDS_MENU_ITEM_CAPTION_HKI_PASS  59
#define IDS_MENU_ITEM_CAPTION_HKI_SFX   60
#define IDS_MENU_ITEM_CAPTION_BGA       61
#define IDS_MENU_ITEM_CAPTION_BZA_SFX   62
#define IDS_MENU_ITEM_CAPTION_GZA_SFX   63
#define IDS_MENU_ITEM_CAPTION_AISH      64
#define IDR_MAINFRAME                   65
#define IDS_MENU_CAPTION_LIST_XACRETT   67
#define IDS_MENU_ITEM_CAPTION_TXZ       69
#define IDS_MENU_ITEM_CAPTION_COMPRESS_B2E 71
#define IDR_MAINFRAME_USERCOMMON        72
#define IDS_MENU_ITEM_CAPTION_TLZ       73
#define IDD_DIALOG_FRAME                101
#define IDD_FORMVIEW_MENU_EDIT          101
#define IDD_DIALOG_VERSION              104
#define IDC_LIST_MENU_ADDED             1000
#define IDC_BUTTON_ADD                  1001
#define IDC_LIST_MENU_SOURCE            1002
#define IDC_BUTTON_DELETE               1003
#define IDC_BUTTON_MOVEUP               1004
#define IDC_BUTTON_MOVEDOWN             1005
#define IDC_BUTTON_RESET                1006
#define IDC_BUTTON_VERSION              1007
#define IDC_LIST_USERMENU               1008
#define IDC_EDIT_USERMENU_CAPTION       1009
#define IDC_BUTTON_ADD_USERMENU         1010
#define IDC_BUTTON_DELETE_USERMENU      1011
#define IDC_BUTTON_MOVEUP_USERMENU      1012
#define IDC_BUTTON_MOVEDOWN_USERMENU    1013
#define IDC_EDIT_USERMENU_PARAM         1014
#define IDC_CHECK_USERMENU_SHELL        1015
#define IDC_CHECK_USERMENU_DRAG         1016

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        107
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1016
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
