//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ で生成されたインクルード ファイル。
// resource.rc で使用
//
#define IDS_MENU_OTHER_OPERATIONS       3
#define IDS_MENU_CAPTION_COMPRESS       4
#define IDS_MENU_CAPTION_OTHER_FORMATS  5
#define IDS_MENU_ITEM_CAPTION_ZSTD      6
#define IDS_MENU_ITEM_CAPTION_TAR_ZSTD  7
#define IDS_MENU_ITEM_CAPTION_ZIP_ROOT  8
#define IDS_MENU_ITEM_CAPTION_LZ4       9
#define IDS_MENU_ITEM_CAPTION_TAR_LZ4   10
#define IDS_PROGRAM_NAME                11
#define IDS_MENU_CAPTION_EXTRACT        13
#define IDS_MENU_CAPTION_COMPRESS_DRAG  14
#define IDS_MENU_CAPTION_EXTRACT_DRAG   15
#define IDS_MENU_CAPTION_EXTRACT_NORMAL 16
#define IDS_MENU_CAPTION_EXTRACT_DESKTOP 17
#define IDS_MENU_CAPTION_EXTRACT_SAME   18
#define IDS_MENU_CAPTION_EXTRACT_TARGET 19
#define IDS_MENU_ITEM_CAPTION_ZIP       23
#define IDS_MENU_ITEM_CAPTION_ZIP_PASS  25
#define IDS_MENU_ITEM_CAPTION_7Z        29
#define IDS_MENU_ITEM_CAPTION_TAR       32
#define IDS_MENU_ITEM_CAPTION_GZ        33
#define IDS_MENU_ITEM_CAPTION_BZ2       34
#define IDS_MENU_ITEM_CAPTION_TGZ       35
#define IDS_MENU_ITEM_CAPTION_TBZ       36
#define IDS_MENU_CAPTION_LIST           39
#define IDS_MENU_CAPTION_OPERATION      40
#define IDS_MENU_ITEM_CAPTION_XZ        41
#define IDS_MENU_ITEM_CAPTION_LZMA      42
#define IDS_MENU_ITEM_CAPTION_TAR_RELATED 58
#define IDS_MENU_CAPTION_TEST_ARCHIVE   68
#define IDS_MENU_ITEM_CAPTION_TXZ       69
#define IDS_MENU_CAPTION_LHAFORGE       70
#define IDS_MENU_ITEM_CAPTION_TLZ       73

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        103
#define _APS_NEXT_COMMAND_VALUE         40002
#define _APS_NEXT_CONTROL_VALUE         1000
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
