//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ で生成されたインクルード ファイル。
// resource.rc で使用
//
#define IDS_DEFAULT_MENU_CAPTION        1
#define IDS_DEFAULT_STATUS_CAPTION      2
#define IDS_MENU_CAPTION_B2E_COMPRESS_POPUP 3
#define IDS_MENU_OTHER_OPERATIONS       3
#define IDS_MENU_CAPTION_COMPRESS       4
#define IDS_MENU_CAPTION_DETAIL         5
#define IDS_MENU_CAPTION_OTHER          5
#define IDS_MENU_CAPTION_OTHER_FORMATS  5
#define IDS_ERROR_MSG_PARAM_OVERFLOW    9
#define IDS_ERROR_MSG_FAILURE_EXECUTE   10
#define IDS_PROGRAM_NAME                11
#define IDS_MENU_CAPTION_EXTRACT        13
#define IDS_MENU_CAPTION_COMPRESS_DRAG  14
#define IDS_MENU_CAPTION_EXTRACT_DRAG   15
#define IDS_MENU_CAPTION_EXTRACT_NORMAL 16
#define IDS_MENU_CAPTION_EXTRACT_DESKTOP 17
#define IDS_MENU_CAPTION_EXTRACT_SAME   18
#define IDS_MENU_CAPTION_EXTRACT_TARGET 19
#define IDS_INPUT_TARGET_FOLDER         20
#define IDS_MENU_ITEM_CAPTION_LZH       21
#define IDS_MENU_ITEM_CAPTION_LZH_SFX   22
#define IDS_MENU_ITEM_CAPTION_ZIP       23
#define IDS_MENU_ITEM_CAPTION_ZIP_SFX   24
#define IDS_MENU_ITEM_CAPTION_ZIP_PASS  25
#define IDS_MENU_ITEM_CAPTION_ZIP_PASS_SFX 26
#define IDS_MENU_ITEM_CAPTION_CAB       27
#define IDS_MENU_ITEM_CAPTION_CAB_SFX   28
#define IDS_MENU_ITEM_CAPTION_7Z        29
#define IDS_MENU_ITEM_CAPTION_7Z_PASS   30
#define IDS_MENU_ITEM_CAPTION_7Z_SFX    31
#define IDS_MENU_ITEM_CAPTION_TAR       32
#define IDS_MENU_ITEM_CAPTION_GZ        33
#define IDS_MENU_ITEM_CAPTION_BZ2       34
#define IDS_MENU_ITEM_CAPTION_TGZ       35
#define IDS_MENU_ITEM_CAPTION_TBZ       36
#define IDS_MENU_ITEM_CAPTION_JACK      37
#define IDS_MENU_ITEM_CAPTION_JACK_SFX  38
#define IDS_MENU_CAPTION_LIST           39
#define IDS_MENU_CAPTION_OPERATION      40
#define IDS_MENU_ITEM_CAPTION_XZ        41
#define IDS_MENU_ITEM_CAPTION_LZMA      42
#define IDS_MENU_ITEM_CAPTION_YZ1       43
#define IDS_MENU_ITEM_CAPTION_YZ1_PASS  44
#define IDS_MENU_ITEM_CAPTION_YZ1_PASS_SFX 45
#define IDS_MENU_ITEM_CAPTION_YZ1_SFX   46
#define IDS_MENU_ITEM_CAPTION_YZ1_PUB_PASS 47
#define IDS_MENU_ITEM_CAPTION_YZ1_PUB_PASS_SFX 48
#define IDS_MENU_ITEM_CAPTION_HKI       49
#define IDS_MENU_ITEM_CAPTION_BZA       50
#define IDS_MENU_ITEM_CAPTION_GZA       51
#define IDS_MENU_ITEM_CAPTION_ISH       52
#define IDS_MENU_ITEM_CAPTION_UUE       53
#define IDS_MENU_ITEM_CAPTION_ZIP_SPLIT 54
#define IDS_MENU_ITEM_CAPTION_ZIP_PASS_SPLIT 55
#define IDS_MENU_ITEM_CAPTION_7Z_SPLIT  56
#define IDS_MENU_ITEM_CAPTION_7Z_PASS_SPLIT 57
#define IDS_MENU_ITEM_CAPTION_TAR_RELATED 58
#define IDS_MENU_ITEM_CAPTION_HKI_PASS  59
#define IDS_MENU_ITEM_CAPTION_HKI_SFX   60
#define IDS_MENU_ITEM_CAPTION_BGA       61
#define IDS_MENU_ITEM_CAPTION_BZA_SFX   62
#define IDS_MENU_ITEM_CAPTION_GZA_SFX   63
#define IDS_MENU_ITEM_CAPTION_AISH      64
#define IDS_MENU_CAPTION_XACRETT        65
#define IDS_MENU_CAPTION_XACRETT_DRAG   66
#define IDS_MENU_CAPTION_LIST_XACRETT   67
#define IDS_MENU_CAPTION_TEST_ARCHIVE   68
#define IDS_MENU_ITEM_CAPTION_TXZ       69
#define IDS_MENU_CAPTION_LHAFORGE       70
#define IDS_MENU_ITEM_CAPTION_COMPRESS_B2E 71
#define IDS_MENU_CAPTION_B2E            72
#define IDS_MENU_ITEM_CAPTION_XZ2       73
#define IDS_MENU_ITEM_CAPTION_TLZ       73

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        103
#define _APS_NEXT_COMMAND_VALUE         40002
#define _APS_NEXT_CONTROL_VALUE         1000
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
